Fix warning on OpenBSD strlcpy.c:73:0: error: ISO C forbids an empty translation unit [-Werror=pedantic]
strlcpy/strlcat functions are defined on OpenBSD, this means
the files are empty, and the warning appears.

This moves an include before of #ifndef
so the files are never empty