Squashed 'libs/libhtp/' changes from 4cb1b99..dbf2452
dbf2452 htp/htp_util.c: Do not invoke callbacks in htp_req_run_hook_body_data() when there is no tx running.
127bbdf Fix make distcheck
b1bb219 QA: add make distcheck to travis CI builds
89c520f Make including the autoconf config header safer, resolving issue #99.
81aa3b5 Update for 0.5.17.
1a6c946 Fix URI parsing for non-std 'space' chars
9d99cc8 Fix warning on OpenBSD strlcpy.c:73:0: error: ISO C forbids an empty translation unit [-Werror=pedantic]
79c2e9e htp_private: include config.h header
c294419 Fix dereferencing type-punned pointer on CentOS 5.11
289d618 strlcpy/strlcat: specify argument types
1bfa33f Fix autogen on CentOS 5.11
bc32db4 test_hybrid.cpp: fix whitespace
cc71947 test_hybrid.cpp: Fixing buffer overrun that was failing clang -fsanitize=address checks.
88da78f Replace strcat/sprintf by strlcat/snprintf
927df72 Add strlcpy/strlcat functions

git-subtree-dir: libs/libhtp
git-subtree-split: dbf24522cad58734009773ce187fc40e2ab4b5de